apiVersion: v1
kind: Pod
metadata:
  name: mssql-pod
  labels:
     app: microservice-seguridad
     name: mssql-pod
spec:
  containers:
    - name: microservice-libreria-app
      image: rapidfort/microsoft-sql-server-2019-ib
      ports:
        - containerPort: 1433
      env:
        - name: ACCEPT_EULA
          value: "Y"
        - name: SA_PASSWORD
          value: "$erochacr2024"