apiVersion: apps/v1
kind: Deployment
metadata:
  name: mssql-deploy
  labels:
    name: mssql-deploy
    app: microservice-seguridad
spec:
  replicas: 1
  selector:
    matchLabels:
      app: microservice-seguridad
      name: mssql-pod
  template:
    metadata:
      name: mssql-pod
      labels:
        app: microservice-seguridad
        name: mssql-pod
    spec:
      containers:
        - name: mssql
          image: rapidfort/microsoft-sql-server-2019-ib
          ports:
            - containerPort: 1433
          env:
            - name: ACCEPT_EULA
              value: "Y"
            - name: SA_PASSWORD
              value: "$erochacr2024"
